services: mongodb

node_js:
  - "node"
  - "6"
  - "8"
  - "10"

sudo: false

env:
  - MONGO_CONNECTIONSTRING="mongodb://localhost:27017/starterkit"

script:
  - npm install --prefix ./backend
  - npm run lint --prefix ./backend
  - npm run test:coverage --prefix ./backend

after_script:
  - "npm install coveralls"
  - "cat ./backend/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
