version: '2'
services:
  app:
    build: .
    env_file: backend/.env-docker.list
    command: node_modules/.bin/nodemon src/index.js --inspect=0.0.0.0:9229 --exec babel-node
    tty: true
    ports:
      - 2000:2000
      - 9229:9229
    volumes:
     - ./backend:/app/backend
     - ./frontend:/app/frontend
    links:
      - mongo
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
