version: '2'
services:
  app:
    build: .
    env_file: backend/.env-docker.list
    tty: true
    command: "npm run test"
    ports:
      - 2000:2000
    links:
      - mongo
  mongo:
    image: mongo:3.2
